from __future__ import annotations

import random
import textwrap
from pathlib import Path
from typing import Optional

from PIL import Image, ImageDraw, ImageFont


def _hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    hex_color = hex_color.lstrip("#")
    if len(hex_color) != 6:
        return (100, 100, 200)
    return tuple(int(hex_color[i : i + 2], 16) for i in (0, 2, 4))


async def generate_image_artifact(
    prompt: str,
    output_path: str | Path,
    width: int = 1280,
    height: int = 900,
    palette: Optional[list[str]] = None,
) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    if palette is None:
        palette = ["#0a1428", "#1a3a6a"]

    image = Image.new("RGB", (width, height))
    draw = ImageDraw.Draw(image)

    bg_gradient(draw, width, height, _hex_to_rgb(palette[0]), _hex_to_rgb(palette[1]))

    accent = _hex_to_rgb(palette[1]) if len(palette) > 1 else (100, 150, 255)

    center_x, center_y = width // 2, height // 2 - 40
    for r in range(200, 50, -30):
        alpha = int(255 * (1 - r / 200))
        color = (
            min(255, accent[0] + random.randint(-30, 30)),
            min(255, accent[1] + random.randint(-30, 30)),
            min(255, accent[2] + random.randint(-30, 30)),
        )
        draw.ellipse(
            (center_x - r, center_y - r, center_x + r, center_y + r),
            fill=(*color, alpha) if hasattr(draw, "fill") else color,
        )

    for i in range(3):
        x = width // 4 + i * width // 3 - 60
        y = height // 2 + 60 + i * 40
        draw.rounded_rectangle(
            (x, y, x + 120 + i * 30, y + 8),
            radius=4,
            fill=(*accent[:3], 60) if hasattr(draw, "fill") else accent,
        )

    try:
        font_large = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 36)
        font_small = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 18)
    except Exception:
        font_large = ImageFont.load_default()
        font_small = ImageFont.load_default()

    title = (prompt or "Generated Image")[:80]
    title_lines = textwrap.wrap(title, width=40)
    y_text = 80
    for line in title_lines[:3]:
        draw.text((width // 2 - len(line) * 9, y_text), line, fill="white", font=font_large)
        y_text += 50

    draw.text((width // 2 - 100, height - 60), "Generated by my_custom_llm", fill=(180, 200, 230), font=font_small)

    image.save(path)
    return path


def bg_gradient(
    draw: ImageDraw.ImageDraw,
    width: int,
    height: int,
    color_top: tuple[int, int, int],
    color_bottom: tuple[int, int, int],
) -> None:
    for y in range(height):
        ratio = y / max(1, height - 1)
        r = int(color_top[0] + (color_bottom[0] - color_top[0]) * ratio)
        g = int(color_top[1] + (color_bottom[1] - color_top[1]) * ratio)
        b = int(color_top[2] + (color_bottom[2] - color_top[2]) * ratio)
        draw.line((0, y, width, y), fill=(r, g, b))
