MODEL_CONFIGS = {
    "micro": {
        "d_model": 32,
        "num_layers": 2,
        "num_heads": 4,
        "ff_hidden_size": 128,
        "block_size": 64,
        "dropout": 0.1,
    },
    "small": {
        "d_model": 64,
        "num_layers": 4,
        "num_heads": 8,
        "ff_hidden_size": 256,
        "block_size": 128,
        "dropout": 0.1,
    },
    "base": {
        "d_model": 128,
        "num_layers": 6,
        "num_heads": 8,
        "ff_hidden_size": 512,
        "block_size": 256,
        "dropout": 0.1,
    },
    "medium": {
        "d_model": 256,
        "num_layers": 8,
        "num_heads": 8,
        "ff_hidden_size": 1024,
        "block_size": 512,
        "dropout": 0.1,
    },
    "large": {
        "d_model": 512,
        "num_layers": 12,
        "num_heads": 16,
        "ff_hidden_size": 2048,
        "block_size": 1024,
        "dropout": 0.1,
    },
    "xl": {
        "d_model": 768,
        "num_layers": 24,
        "num_heads": 16,
        "ff_hidden_size": 3072,
        "block_size": 2048,
        "dropout": 0.1,
    },
    "winner-1b": {
        "d_model": 1024,
        "num_layers": 16,
        "num_heads": 16,
        "ff_hidden_size": 4096,
        "block_size": 2048,
        "dropout": 0.1,
    },
    "winner-7b": {
        "d_model": 4096,
        "num_layers": 32,
        "num_heads": 32,
        "ff_hidden_size": 16384,
        "block_size": 4096,
        "dropout": 0.1,
    },
    "winner-70b": {
        "d_model": 8192,
        "num_layers": 80,
        "num_heads": 64,
        "ff_hidden_size": 32768,
        "block_size": 8192,
        "dropout": 0.1,
    },
}
